version: "3"

services:
  service-accounts-database:
    container_name: service-accounts-database
    image: postgres:latest
    # expose:
    #   - 3000
    volumes:
      - ./service-accounts-database/database:/database:rw
    ports:
      - 3001:3001
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/database
    command: postgres -c log_statement=all -p 3001